### ISSUE TITLE
nanmean() has moved from scipy.stats

### ISSUE THREAD

**Issue by wagglefoot** [moorepants/DynamicistToolKit#33]
It would appear that `nanmean()` has moved from `scipy.stats` to `scipy`; see [here](https://docs.scipy.org/doc/scipy/reference/stats.html).

Currently `from scipy.stats import nanmean` in `process.py` yields an import failure, but works when changed to `from scipy import nanmean`. 

I don't know if you want me to issue a PR or just change as done here.

**Comment by moorepants** [comment]
PR would gladly be accepted. Please make it work with earlier and later versions of scipy if you do.
